# Deep-subspace-clustering-networks
My GitHub：https://github.com/Elliot-Wang/DSC-rebuilt.git  
My Account：15260223133@163.com

In [1]:
!pip install munkres==1.0.8
#!pip install tensorflow==1.14.0
%tensorflow_version 1.x
!git clone https://github.com/Elliot-Wang/DSC-rebuilt.git
!mv DSC-rebuilt/*.py ./

  Created wheel for munkres: filename=munkres-1.0.8-cp36-none-any.whl size=11236 sha256=267ea078e119da532a47bcc2557c320e12b86e019ad7588a7fdeb7625f4236ac
  Stored in directory: /root/.cache/pip/wheels/9f/61/27/66dfa0b5b370aca085ef8dfbe49b6b6d0763f26c3d82f51e5d
Successfully built munkres
Cloning into 'DSC-rebuilt'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 65 (delta 28), reused 57 (delta 20), pack-reused 0
Unpacking objects: 100% (65/65), done.


In [2]:
!python DSC_Net_L2_EYaleB.py



Traceback (most recent call last):
  File "DSC_Net_L2_EYaleB.py", line 341, in <module>
    restore_path=restore_path, logs_path=logs_path)
  File "DSC_Net_L2_EYaleB.py", line 28, in __init__
    self.x = tf.placeholder(tf.float32, [None, n_input[0], n_input[1], 1], name='input image')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 411, in _apply_op_helper
    with g.as_default(), ops.name_scope(name) as scope:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 6346, in __enter__
    return self._name_scope.__enter__()
  File "

In [0]:
def get_data(addr):
    data = sio.loadmat(addr)
    img = data['Y']
    I = []
    Label = []
    for i in range(img.shape[2]):
        for j in range(img.shape[1]):
            temp = np.reshape(img[:, j, i],[42, 48])
            Label.append(i)
            I.append(temp)
    I = np.array(I)
    Label = np.array(Label[:])
    Img = np.transpose(I,[0, 2, 1])
    Img = np.expand_dims(Img[:], 3)
    return Img, Label

In [0]:
import scipy.io as sio
import numpy as np

img, label = get_data('DSC/Data/YaleBCrop025.mat')

In [14]:
mat = np.array([[1, 2], [3, 4], [5, 6]])
print(mat)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
rmat = np.reshape(mat, [6, 1])
print(rmat)
rrmat = np.reshape(mat, [3, 2])
print(rrmat)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(img.shape[0])
print(img.shape[1])
print(img.shape[2])

2432
48
42


In [20]:
data = sio.loadmat('DSC/Data/YaleBCrop025.mat')
Img = data['Y']
print(Img.shape[0])
print(Img.shape[1])
print(Img.shape[2])

2016
64
38


In [21]:
Img = np.array(Img)
print(Img.shape[0])
print(Img.shape[1])
print(Img.shape[2])

2016
64
38


In [26]:
# L2 regularization
all_subjects = [10, 15, 20, 25, 30, 35, 38]
print('L2 regularization', '*'*10)
for num_class in all_subjects:
    print(1.0 * 10 ** (num_class / 10.0 - 3.0))
print('alpha set', '*'*10)
for num_class in all_subjects:
    print(max(0.4 - (num_class-1)/10 * 0.1, 0.1))

L2 regularization **********
0.01
0.03162277660168379
0.1
0.31622776601683794
1.0
3.1622776601683795
6.30957344480193
alpha set **********
0.31
0.26
0.21000000000000002
0.16000000000000003
0.11000000000000004
0.1
0.1


In [2]:
import DSC.DSC_Net_L2_EYaleB as yale
Img, Label = yale.get_data('DSC/Data/YaleBCrop025.mat')

n_input = [48, 42]
kernel_size = [5, 3, 3]
n_hidden = [10, 20, 30]

all_subjects = [10, 15, 20, 25, 30, 35, 38]

avg = []
med = []

model_path = 'DSC/pretrain-model-EYaleB/model-102030-48x42-yaleb.ckpt' 
restore_path = 'DSC/pretrain-model-EYaleB/model-102030-48x42-yaleb.ckpt' 
logs_path = 'DSC/pretrain-model-EYaleB/logs' 

num_class = all_subjects[0]
batch_size = num_class * 64
reg1 = 1.0
reg2 = 10 ** (num_class / 10.0 -3.0)
cae = yale.ConvAE(n_input=n_input, n_hidden=n_hidden, reg_constant1=reg1, re_constant2=reg2, \
                     kernel_size=kernel_size, batch_size=batch_size, model_path=model_path, \
                         restore_path=restore_path, logs_path=logs_path)
cae.initlization()
cae.restore()






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where







In [10]:
import numpy as  np
face = np.array( Img[0: 64*num_class, :]).astype(float)
cost, Coef = cae.partial_fit(face, 1.0e-3)
print('epoch 001:')

In [12]:
print('cost is %e' % cost)

cost is 4.694987e+09


In [13]:
print('epoch 101:')
for i in range(100):
    cost, Coef = cae.partial_fit(face, 1.0e-3)
print('cost is %e' % cost)

cost is 1.879936e+08


In [14]:
print('epoch 201:')
for i in range(100):
    cost, Coef = cae.partial_fit(face, 1.0e-3)
print('cost is %e' % cost)
print('epoch 301:')
for i in range(100):
    cost, Coef = cae.partial_fit(face, 1.0e-3)
print('cost is %e' % cost)

cost is 8.958950e+07
cost is 5.853048e+07


In [19]:
print(Coef.shape)

(640, 640)


In [20]:
cp = np.zeros(Coef.shape)
print(np.shape(Coef))

(640, 640)


In [30]:
from PIL import Image
Cmax = np.max(Coef)
Cmin = np.min(Coef)
im = Image.fromarray((Coef - Cmin) * 255 / (Cmax - Cmin))
im.show() # Coef数值太小了，以至于一片黑

In [33]:
S = np.abs(np.sort(-1*np.abs(Coef), axis=0))
absMax = np.max(np.abs(S))
im = Image.fromarray(S/absMax*255)
im.show()

In [37]:
Ind = np.argsort(-1*np.abs(Coef), axis=0)
absMax = np.max(np.abs(Ind))
im = Image.fromarray(Ind/absMax*255)
im.show() # 乱七八糟的这个图

In [4]:
import numpy as np
import tensorflow as tf
x = tf.Variable(tf.ones([2, 2]), tf.float32)
x.get_shape()

C:\Users\15524\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\15524\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\15524\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\15524\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

TensorShape([Dimension(2), Dimension(2)])

In [7]:
# YaleB dataset
import DSC.DSC as dsc
import tensorflow as tf
data_set = 'Yale'
img, label = dsc.get_data(data_set)
path = dsc.get_path(data_set)

net_struc = {'input':[48, 42], 'kernel':[5, 3, 3], 'hidden':[10, 20, 30], 'batch':[]}
regular = {'reg_1':1.0, 'reg_2':1.0, 'reg':1.0}
all_subjects = [10, 15, 20, 25, 30, 35, 38]
avg = []
med = []
for i in range(len(all_subjects)):
    num_class = all_subjects[i]
    net_struc['batch'] = num_class * 64
    regular['reg_2'] = 10 ** (num_class / 10.0 - 3.0)
    
    tf.reset_default_graph()
    cae = dsc.ConvAE(net_struc, path, regular)
    # train function *****
    avg_i, med_i = dsc.test_face(img, label, cae, num_class)
    avg.append(avg_i)
    med.append(med_i)

# print result
for i in range(len(all_subjects)):
    num_class = all_subjects[i]
    print ('%d subjects:' % num_class)
    print ('Mean: %.4f%%' % (avg[i]*100), 'Median: %.4f%%' % (med[i]*100)) 

[2, 2]